//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberLearnHub.Admin
{
    public partial class ContactMessages
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.Label lblAlert;
        protected global::System.Web.UI.WebControls.Panel pnlDetail;
        protected global::System.Web.UI.WebControls.Literal litDetailSubject;
        protected global::System.Web.UI.WebControls.Literal litDetailName;
        protected global::System.Web.UI.WebControls.Literal litDetailEmail;
        protected global::System.Web.UI.WebControls.Literal litDetailDate;
        protected global::System.Web.UI.WebControls.Literal litDetailMessage;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor aReply;
        protected global::System.Web.UI.WebControls.Button btnCloseDetail;
        protected global::System.Web.UI.WebControls.Label lblUnreadBadge;
        protected global::System.Web.UI.WebControls.Button btnMarkAllRead;
        protected global::System.Web.UI.WebControls.Repeater rptMessages;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
    }
}
