//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberLearnHub
{
    public partial class ManageLabs
    {
        protected global::System.Web.UI.WebControls.LinkButton btnShowAddForm;
        protected global::System.Web.UI.WebControls.Label lblStatusMsg;
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        protected global::System.Web.UI.WebControls.Literal litFormTitle;
        protected global::System.Web.UI.WebControls.HiddenField hdnLabId;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.TextBox txtTargetInfo;
        protected global::System.Web.UI.WebControls.TextBox txtFlag;
        protected global::System.Web.UI.WebControls.Label lblFlagHint;
        protected global::System.Web.UI.WebControls.TextBox txtPoints;
        protected global::System.Web.UI.WebControls.DropDownList ddlDifficulty;
        protected global::System.Web.UI.WebControls.CheckBox chkIsActive;
        protected global::System.Web.UI.WebControls.LinkButton btnSave;
        protected global::System.Web.UI.WebControls.LinkButton btnCancelForm;
        protected global::System.Web.UI.WebControls.Panel pnlMaterials;
        protected global::System.Web.UI.WebControls.Panel pnlMaterialsList;
        protected global::System.Web.UI.WebControls.Panel pnlUploadRow;
        protected global::System.Web.UI.WebControls.Repeater rptMaterials;
        protected global::System.Web.UI.WebControls.Label lblNoMaterials;
        protected global::System.Web.UI.WebControls.FileUpload fuMaterial;
        protected global::System.Web.UI.WebControls.LinkButton btnUploadMaterial;
        protected global::System.Web.UI.WebControls.GridView gvLabs;
    }
}
