//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberLearnHub
{
    public partial class AccessDenied
    {
        protected global::System.Web.UI.WebControls.Panel pnlDesktopRequired;
        protected global::System.Web.UI.WebControls.Panel pnlAccessDenied;
        protected global::System.Web.UI.WebControls.Panel pnlLoginLink;
        protected global::System.Web.UI.WebControls.Label lblDesktopMsg;
    }
}
