//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberLearnHub
{
    public partial class ForgotPassword
    {
        /// <summary>
        /// txtEmail control.
        /// Auto-generated field.
        /// To modify, move field declaration from designer file to code-behind file.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// btnSendReset control.
        /// Auto-generated field.
        /// To modify, move field declaration from designer file to code-behind file.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSendReset;

        /// <summary>
        /// lblMessage control.
        /// Auto-generated field.
        /// To modify, move field declaration from designer file to code-behind file.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
