//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberLearnHub
{
    public partial class Site
    {
        protected global::System.Web.UI.WebControls.Panel pnlGuestButtons;
        protected global::System.Web.UI.WebControls.Panel pnlUserButtons;
        protected global::System.Web.UI.WebControls.Panel pnlUserNav;
        protected global::System.Web.UI.WebControls.Panel pnlAdminNav;
        protected global::System.Web.UI.WebControls.Label lblNavUsername;
        protected global::System.Web.UI.WebControls.Button btnLogin;
        protected global::System.Web.UI.WebControls.Button btnRegister;
        protected global::System.Web.UI.WebControls.Button btnLogout;
        protected global::System.Web.UI.WebControls.HyperLink hlProfile;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
